
import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ndirituedwin
 */
public class Membership extends javax.swing.JFrame {
    DefaultTableModel dm;
    Connection conn;
    ResultSet rs=null;
    PreparedStatement pst;
    Statement stmt;
    String Group_Name,Name,Id_No,Tel_No,Group_Id,Date;
    /**
     * Creates new form Membership
     */
    public Membership() {
        initComponents();
        conn=Dbconnection.Dbconnection();
        dm=(DefaultTableModel)jTable1.getModel();
        showvaluesfromdatabasetocombobox();
        try{
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        showtablemembership();
       
    }
    private void showtablemembership(){
        try{
           String sql="select*from membership";
            pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    private void enterr(){
       try{
           String insert="insert into membership(`Group_Id`,`Name`,`Id_No`,`Tel_No`,`Date`)values (?,?,?,?,?)";
           pst=conn.prepareStatement(insert); 
           pst.setString(2,txtname.getText());
           pst.setString(3,txtidno.getText());
            pst.setString(4,txttelno.getText());
            pst.setString(5,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            String value=cmbgroupname.getSelectedItem().toString();
            int Id1=Integer.parseInt(value);
            pst.setString(1, value);
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null,"inserted");
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,ex);
       }
    }
    private void showvaluesfromdatabasetocombobox(){
        try{
           Statement stmt=(Statement)conn.createStatement();
            String sql="select Rec_Id from groups";
            ResultSet rs=stmt.executeQuery(sql);
           while(rs.next()){
               String Group_Name=rs.getString("Rec_Id");
               cmbgroupname.addItem(Group_Name);
//                cmbgroupname.addItem(Integer.toString(rs.getInt("Group_Id")));
               
           }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    private void emptyfields(){
        try{
            txtsearch.setText("");
            jDateChooser1.setDate(null);
            cmbgroupname.setSelectedIndex(0);
            txtname.setText("");
            txtidno.setText("");
            txttelno.setText("");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txttelno = new javax.swing.JTextField();
        txtidno = new javax.swing.JTextField();
        cmbgroupname = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Searchfilter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 62, -1));

        jLabel2.setText("Group_Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setText("Id_No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setText("Tel_No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 200, -1));
        getContentPane().add(txttelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 200, -1));
        getContentPane().add(txtidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 200, -1));

        cmbgroupname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select group id" }));
        cmbgroupname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgroupnameActionPerformed(evt);
            }
        });
        getContentPane().add(cmbgroupname, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 56, 190, -1));

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 380, 230));

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton2.setText("Empty");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             enterr();
            showtablemembership();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbgroupnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgroupnameActionPerformed
        // TODO add your handling code here:
        try{
//            int id1=Integer.parseInt(Group_Name);
//            Statement stmt=(Statement)conn.createStatement();
//            String sql="select Group_Id from membership";
//            ResultSet rs=stmt.executeQuery(sql);
//            while(rs.next()){
//                cmbgroupname.addItem(Integer.toString(rs.getInt("Group_Id")));
//               
//            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_cmbgroupnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            emptyfields();
            showtablemembership();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
//        int raw=jTable1.getSelectedRow();
//       String va=jTable1.getModel().getValueAt(raw, 4).toString();
//       try{
//       cmbgroupname.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
//       txtname.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
//       txtidno.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
//      txttelno.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
//              
//       }catch(Exception ex){
//           JOptionPane.showMessageDialog(null,ex);
//       }
       
       
//     String va=jTable1.setModel().getvalueA
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ro=jTable1.getSelectedRow();
        String v=jTable1.getModel().getValueAt(ro,5).toString();
       JOptionPane.showMessageDialog(null,ro+"  "+v);
         try{
            String value1=txtname.getText();
            String value2=txtidno.getText();
            String value3=txttelno.getText();
       String sql="update membership set Name='"+value1+"',Id_No='"+value2+"',Tel_No='"+value3+"',Date='"+value3+"' where Rec_Id='"+Integer.parseInt(v)+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       pst.executeUpdate();
       showtablemembership();
       JOptionPane.showMessageDialog(null,"updated");
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex);
         }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int ro=jTable1.getSelectedRow();
        String va=jTable1.getModel().getValueAt(ro,4).toString();
//          JOptionPane.showMessageDialog(null,ro);
        int confirmdelete=JOptionPane.showConfirmDialog(null, "Do you really want to delete this row?","Delete",JOptionPane.YES_NO_OPTION);
        String delete="delete from membership where Rec_Id='"+ro+"'";
        try{
            pst=conn.prepareStatement(delete);
            pst.execute();
            showtablemembership();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        //search with name argument add display in textfields;
//      try{
//          String sql="select*from Membership where Name=?";
//          pst=conn.prepareStatement(sql);
//          pst.setString(1,txtsearch.getText());
//          rs=pst.executeQuery();
//          if(rs.next()){
//              String add1=rs.getString("Group_Id");
//              cmbgroupname.setSelectedItem(add1);
//              String add2=rs.getString("Name");
//              txtname.setText(add2);
//              String add3=rs.getString("Id_No");
//              txtidno.setText(add3);
//              String add4=rs.getString("Tel_No");
//              txttelno.setText(add4);
//              
//          }
//      }catch(Exception ex){
//          JOptionPane.showMessageDialog(null,ex);
//      }
       try{
          String sql="select*from Membership where Rec_Id=?";
          pst=conn.prepareStatement(sql);
          pst.setString(1,txtsearch.getText());
          rs=pst.executeQuery();
          if(rs.next()){
              String add1=rs.getString("Group_Id");
              cmbgroupname.setSelectedItem(add1);
              String add2=rs.getString("Name");
              txtname.setText(add2);
              String add3=rs.getString("Id_No");
              txtidno.setText(add3);
              String add4=rs.getString("Tel_No");
              txttelno.setText(add4);
              Date add5=rs.getDate("Date");
              jDateChooser1.setDate(add5);
              
              showtablemembership();
          }
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex);
      }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
//              if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_UP){
//                        try{
//              int ro=jTable1.getSelectedRow();
//              String va=jTable1.getModel().getValueAt(ro,5).toString();
//              String sql="select*from membership where Rec_Id='"+Integer.parseInt(va)+"'";
//              pst=conn.prepareStatement(sql);
//              rs=pst.executeQuery();
//                 if(rs.next()){
//                     String add1=rs.getString("Group_Id");
//                     cmbgroupname.setSelectedItem(add1);
//                     String add2=rs.getString("Name");
//                     txtname.setText(add2);
//                     String add3=rs.getString("Id_No");
//                     txtidno.setText(add3);
//                     String add4=rs.getString("Tel_No");
//                     txttelno.setText(add4);
//                     Date add5=rs.getDate("Date");
//                     jDateChooser1.setDate(add5);
//              
//              showtablemembership();
//                 }
//                
//            }catch(Exception ex){
//                JOptionPane.showMessageDialog(null,ex);
//            }
//        
//              }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_UP){
                        try{
              int ro=jTable1.getSelectedRow();
              String va=jTable1.getModel().getValueAt(ro,5).toString();
              String sql="select*from membership where Rec_Id='"+va+"'";
              pst=conn.prepareStatement(sql);
              rs=pst.executeQuery();
                 if(rs.next()){
                     String add1=rs.getString("Group_Id");
                     cmbgroupname.setSelectedItem(add1);
                     String add2=rs.getString("Name");
                     txtname.setText(add2);
                     String add3=rs.getString("Id_No");
                     txtidno.setText(add3);
                     String add4=rs.getString("Tel_No");
                     txttelno.setText(add4);
                     Date add5=rs.getDate("Date");
                     jDateChooser1.setDate(add5);
              
              showtablemembership();
                 }
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        
              }
//               int raw=jTable1.getSelectedRow();
////       String va=jTable1.getModel().getValueAt(raw, 4).toString();
////       try{
////       cmbgroupname.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
////       txtname.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
////       txtidno.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
////      txttelno.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
////              
////       }catch(Exception ex){
////           JOptionPane.showMessageDialog(null,ex);
////       }
////       
////          }
//     String va=jTable1.setModel().getvalueA
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Membership.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Membership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbgroupname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtidno;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttelno;
    // End of variables declaration//GEN-END:variables
}
